// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/core/backend/proto/user.proto
// Protobuf Java Version: 4.29.3

package org.core.backend;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string _id = 18;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string _id = 18;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 19;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 19;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string locationName = 20;</code>
   * @return The locationName.
   */
  java.lang.String getLocationName();
  /**
   * <code>string locationName = 20;</code>
   * @return The bytes for locationName.
   */
  com.google.protobuf.ByteString
      getLocationNameBytes();

  /**
   * <code>string imageUrl = 21;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string imageUrl = 21;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
