// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/core/backend/proto/user.proto
// Protobuf Java Version: 4.29.3

package org.core.backend;

public final class UserServiceProto {
  private UserServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      UserServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Role_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_Role_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/java/org/core/backend/proto/u" +
      "ser.proto\022\004user\032\033google/protobuf/empty.p" +
      "roto\"\254\002\n\004User\022\013\n\003_id\030\001 \001(\t\022\021\n\tfirstName\030" +
      "\002 \001(\t\022\025\n\rpostalAddress\030\003 \001(\t\022\022\n\ntelephon" +
      "e1\030\004 \001(\t\022\022\n\ntelephone2\030\005 \001(\t\022\020\n\010username" +
      "\030\006 \001(\t\022\020\n\010lastName\030\007 \001(\t\022\r\n\005email\030\010 \001(\t\022" +
      "\026\n\016organisationId\030\t \001(\t\022\013\n\003uid\030\n \001(\t\022\031\n\005" +
      "roles\030\013 \003(\0132\n.user.Role\022 \n\010location\030\014 \001(" +
      "\0132\016.user.Location\022\016\n\006active\030\r \001(\010\022\020\n\010app" +
      "roved\030\016 \001(\010\022\016\n\006feduid\030\017 \001(\t\"#\n\004Role\022\014\n\004n" +
      "ame\030\020 \001(\t\022\r\n\005value\030\021 \001(\010\"M\n\010Location\022\013\n\003" +
      "_id\030\022 \001(\t\022\014\n\004name\030\023 \001(\t\022\024\n\014locationName\030" +
      "\024 \001(\t\022\020\n\010imageUrl\030\025 \001(\t2\225\001\n\013UserService\022" +
      "-\n\007GetUser\022\026.google.protobuf.Empty\032\n.use" +
      "r.User\022(\n\016GetUserDetails\022\n.user.User\032\n.u" +
      "ser.User\022-\n\021StreamUserDetails\022\n.user.Use" +
      "r\032\n.user.User0\001B&\n\020org.core.backendB\020Use" +
      "rServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "FirstName", "PostalAddress", "Telephone1", "Telephone2", "Username", "LastName", "Email", "OrganisationId", "Uid", "Roles", "Location", "Active", "Approved", "Feduid", });
    internal_static_user_Role_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_Role_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_user_Location_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_Location_descriptor,
        new java.lang.String[] { "Id", "Name", "LocationName", "ImageUrl", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
