// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/auth/backend/proto/user.proto
// Protobuf Java Version: 4.29.3

package org.core.backend;

public interface RoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Role)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 16;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 16;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool value = 17;</code>
   * @return The value.
   */
  boolean getValue();
}
