// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/auth/backend/proto/user.proto
// Protobuf Java Version: 4.29.3

package org.core.backend;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string _id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string _id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string postalAddress = 3;</code>
   * @return The postalAddress.
   */
  java.lang.String getPostalAddress();
  /**
   * <code>string postalAddress = 3;</code>
   * @return The bytes for postalAddress.
   */
  com.google.protobuf.ByteString
      getPostalAddressBytes();

  /**
   * <code>string telephone1 = 4;</code>
   * @return The telephone1.
   */
  java.lang.String getTelephone1();
  /**
   * <code>string telephone1 = 4;</code>
   * @return The bytes for telephone1.
   */
  com.google.protobuf.ByteString
      getTelephone1Bytes();

  /**
   * <code>string telephone2 = 5;</code>
   * @return The telephone2.
   */
  java.lang.String getTelephone2();
  /**
   * <code>string telephone2 = 5;</code>
   * @return The bytes for telephone2.
   */
  com.google.protobuf.ByteString
      getTelephone2Bytes();

  /**
   * <code>string username = 6;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 6;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string lastName = 7;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 7;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 8;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 8;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string organisationId = 9;</code>
   * @return The organisationId.
   */
  java.lang.String getOrganisationId();
  /**
   * <code>string organisationId = 9;</code>
   * @return The bytes for organisationId.
   */
  com.google.protobuf.ByteString
      getOrganisationIdBytes();

  /**
   * <code>string uid = 10;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 10;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  java.util.List<org.core.backend.Role>
      getRolesList();
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  org.core.backend.Role getRoles(int index);
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  java.util.List<? extends org.core.backend.RoleOrBuilder>
      getRolesOrBuilderList();
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  org.core.backend.RoleOrBuilder getRolesOrBuilder(
      int index);

  /**
   * <code>.user.Location location = 12;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.user.Location location = 12;</code>
   * @return The location.
   */
  org.core.backend.Location getLocation();
  /**
   * <code>.user.Location location = 12;</code>
   */
  org.core.backend.LocationOrBuilder getLocationOrBuilder();

  /**
   * <code>bool active = 13;</code>
   * @return The active.
   */
  boolean getActive();

  /**
   * <code>bool approved = 14;</code>
   * @return The approved.
   */
  boolean getApproved();

  /**
   * <code>string feduid = 15;</code>
   * @return The feduid.
   */
  java.lang.String getFeduid();
  /**
   * <code>string feduid = 15;</code>
   * @return The bytes for feduid.
   */
  com.google.protobuf.ByteString
      getFeduidBytes();
}
