// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/org/auth/backend/proto/user.proto
// Protobuf Java Version: 4.29.3

package org.core.backend;

/**
 * Protobuf type {@code user.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:user.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      User.class.getName());
  }
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private User() {
    Id_ = "";
    firstName_ = "";
    postalAddress_ = "";
    telephone1_ = "";
    telephone2_ = "";
    username_ = "";
    lastName_ = "";
    email_ = "";
    organisationId_ = "";
    uid_ = "";
    roles_ = java.util.Collections.emptyList();
    feduid_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.core.backend.UserServiceProto.internal_static_user_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.core.backend.UserServiceProto.internal_static_user_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.core.backend.User.class, org.core.backend.User.Builder.class);
  }

  private int bitField0_;
  public static final int _ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object Id_ = "";
  /**
   * <code>string _id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = Id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      Id_ = s;
      return s;
    }
  }
  /**
   * <code>string _id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = Id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      Id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object firstName_ = "";
  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTALADDRESS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object postalAddress_ = "";
  /**
   * <code>string postalAddress = 3;</code>
   * @return The postalAddress.
   */
  @java.lang.Override
  public java.lang.String getPostalAddress() {
    java.lang.Object ref = postalAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postalAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string postalAddress = 3;</code>
   * @return The bytes for postalAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPostalAddressBytes() {
    java.lang.Object ref = postalAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postalAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEPHONE1_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object telephone1_ = "";
  /**
   * <code>string telephone1 = 4;</code>
   * @return The telephone1.
   */
  @java.lang.Override
  public java.lang.String getTelephone1() {
    java.lang.Object ref = telephone1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      telephone1_ = s;
      return s;
    }
  }
  /**
   * <code>string telephone1 = 4;</code>
   * @return The bytes for telephone1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTelephone1Bytes() {
    java.lang.Object ref = telephone1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      telephone1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEPHONE2_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object telephone2_ = "";
  /**
   * <code>string telephone2 = 5;</code>
   * @return The telephone2.
   */
  @java.lang.Override
  public java.lang.String getTelephone2() {
    java.lang.Object ref = telephone2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      telephone2_ = s;
      return s;
    }
  }
  /**
   * <code>string telephone2 = 5;</code>
   * @return The bytes for telephone2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTelephone2Bytes() {
    java.lang.Object ref = telephone2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      telephone2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object username_ = "";
  /**
   * <code>string username = 6;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 6;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastName_ = "";
  /**
   * <code>string lastName = 7;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string lastName = 7;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 8;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 8;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORGANISATIONID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object organisationId_ = "";
  /**
   * <code>string organisationId = 9;</code>
   * @return The organisationId.
   */
  @java.lang.Override
  public java.lang.String getOrganisationId() {
    java.lang.Object ref = organisationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      organisationId_ = s;
      return s;
    }
  }
  /**
   * <code>string organisationId = 9;</code>
   * @return The bytes for organisationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrganisationIdBytes() {
    java.lang.Object ref = organisationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      organisationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uid_ = "";
  /**
   * <code>string uid = 10;</code>
   * @return The uid.
   */
  @java.lang.Override
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uid_ = s;
      return s;
    }
  }
  /**
   * <code>string uid = 10;</code>
   * @return The bytes for uid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLES_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private java.util.List<org.core.backend.Role> roles_;
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  @java.lang.Override
  public java.util.List<org.core.backend.Role> getRolesList() {
    return roles_;
  }
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.core.backend.RoleOrBuilder>
      getRolesOrBuilderList() {
    return roles_;
  }
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  @java.lang.Override
  public int getRolesCount() {
    return roles_.size();
  }
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  @java.lang.Override
  public org.core.backend.Role getRoles(int index) {
    return roles_.get(index);
  }
  /**
   * <code>repeated .user.Role roles = 11;</code>
   */
  @java.lang.Override
  public org.core.backend.RoleOrBuilder getRolesOrBuilder(
      int index) {
    return roles_.get(index);
  }

  public static final int LOCATION_FIELD_NUMBER = 12;
  private org.core.backend.Location location_;
  /**
   * <code>.user.Location location = 12;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.user.Location location = 12;</code>
   * @return The location.
   */
  @java.lang.Override
  public org.core.backend.Location getLocation() {
    return location_ == null ? org.core.backend.Location.getDefaultInstance() : location_;
  }
  /**
   * <code>.user.Location location = 12;</code>
   */
  @java.lang.Override
  public org.core.backend.LocationOrBuilder getLocationOrBuilder() {
    return location_ == null ? org.core.backend.Location.getDefaultInstance() : location_;
  }

  public static final int ACTIVE_FIELD_NUMBER = 13;
  private boolean active_ = false;
  /**
   * <code>bool active = 13;</code>
   * @return The active.
   */
  @java.lang.Override
  public boolean getActive() {
    return active_;
  }

  public static final int APPROVED_FIELD_NUMBER = 14;
  private boolean approved_ = false;
  /**
   * <code>bool approved = 14;</code>
   * @return The approved.
   */
  @java.lang.Override
  public boolean getApproved() {
    return approved_;
  }

  public static final int FEDUID_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object feduid_ = "";
  /**
   * <code>string feduid = 15;</code>
   * @return The feduid.
   */
  @java.lang.Override
  public java.lang.String getFeduid() {
    java.lang.Object ref = feduid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      feduid_ = s;
      return s;
    }
  }
  /**
   * <code>string feduid = 15;</code>
   * @return The bytes for feduid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFeduidBytes() {
    java.lang.Object ref = feduid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      feduid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(Id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, Id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(postalAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, postalAddress_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(telephone1_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, telephone1_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(telephone2_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, telephone2_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, username_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, email_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(organisationId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, organisationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, uid_);
    }
    for (int i = 0; i < roles_.size(); i++) {
      output.writeMessage(11, roles_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(12, getLocation());
    }
    if (active_ != false) {
      output.writeBool(13, active_);
    }
    if (approved_ != false) {
      output.writeBool(14, approved_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(feduid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 15, feduid_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(Id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, Id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(postalAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, postalAddress_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(telephone1_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, telephone1_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(telephone2_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, telephone2_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, username_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, email_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(organisationId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, organisationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, uid_);
    }
    for (int i = 0; i < roles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, roles_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getLocation());
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, active_);
    }
    if (approved_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, approved_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(feduid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(15, feduid_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.core.backend.User)) {
      return super.equals(obj);
    }
    org.core.backend.User other = (org.core.backend.User) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getPostalAddress()
        .equals(other.getPostalAddress())) return false;
    if (!getTelephone1()
        .equals(other.getTelephone1())) return false;
    if (!getTelephone2()
        .equals(other.getTelephone2())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getOrganisationId()
        .equals(other.getOrganisationId())) return false;
    if (!getUid()
        .equals(other.getUid())) return false;
    if (!getRolesList()
        .equals(other.getRolesList())) return false;
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (getActive()
        != other.getActive()) return false;
    if (getApproved()
        != other.getApproved()) return false;
    if (!getFeduid()
        .equals(other.getFeduid())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + _ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + POSTALADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getPostalAddress().hashCode();
    hash = (37 * hash) + TELEPHONE1_FIELD_NUMBER;
    hash = (53 * hash) + getTelephone1().hashCode();
    hash = (37 * hash) + TELEPHONE2_FIELD_NUMBER;
    hash = (53 * hash) + getTelephone2().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + ORGANISATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getOrganisationId().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid().hashCode();
    if (getRolesCount() > 0) {
      hash = (37 * hash) + ROLES_FIELD_NUMBER;
      hash = (53 * hash) + getRolesList().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    hash = (37 * hash) + APPROVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getApproved());
    hash = (37 * hash) + FEDUID_FIELD_NUMBER;
    hash = (53 * hash) + getFeduid().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.core.backend.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.core.backend.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.core.backend.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.core.backend.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.core.backend.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.core.backend.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.core.backend.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.core.backend.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.core.backend.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.core.backend.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.core.backend.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.core.backend.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.core.backend.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.User)
      org.core.backend.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.core.backend.UserServiceProto.internal_static_user_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.core.backend.UserServiceProto.internal_static_user_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.core.backend.User.class, org.core.backend.User.Builder.class);
    }

    // Construct using org.core.backend.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRolesFieldBuilder();
        getLocationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      Id_ = "";
      firstName_ = "";
      postalAddress_ = "";
      telephone1_ = "";
      telephone2_ = "";
      username_ = "";
      lastName_ = "";
      email_ = "";
      organisationId_ = "";
      uid_ = "";
      if (rolesBuilder_ == null) {
        roles_ = java.util.Collections.emptyList();
      } else {
        roles_ = null;
        rolesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      location_ = null;
      if (locationBuilder_ != null) {
        locationBuilder_.dispose();
        locationBuilder_ = null;
      }
      active_ = false;
      approved_ = false;
      feduid_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.core.backend.UserServiceProto.internal_static_user_User_descriptor;
    }

    @java.lang.Override
    public org.core.backend.User getDefaultInstanceForType() {
      return org.core.backend.User.getDefaultInstance();
    }

    @java.lang.Override
    public org.core.backend.User build() {
      org.core.backend.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.core.backend.User buildPartial() {
      org.core.backend.User result = new org.core.backend.User(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.core.backend.User result) {
      if (rolesBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0)) {
          roles_ = java.util.Collections.unmodifiableList(roles_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.roles_ = roles_;
      } else {
        result.roles_ = rolesBuilder_.build();
      }
    }

    private void buildPartial0(org.core.backend.User result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.Id_ = Id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.firstName_ = firstName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.postalAddress_ = postalAddress_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.telephone1_ = telephone1_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.telephone2_ = telephone2_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.username_ = username_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.lastName_ = lastName_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.organisationId_ = organisationId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.uid_ = uid_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.location_ = locationBuilder_ == null
            ? location_
            : locationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.active_ = active_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.approved_ = approved_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.feduid_ = feduid_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.core.backend.User) {
        return mergeFrom((org.core.backend.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.core.backend.User other) {
      if (other == org.core.backend.User.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        Id_ = other.Id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPostalAddress().isEmpty()) {
        postalAddress_ = other.postalAddress_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTelephone1().isEmpty()) {
        telephone1_ = other.telephone1_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTelephone2().isEmpty()) {
        telephone2_ = other.telephone2_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getOrganisationId().isEmpty()) {
        organisationId_ = other.organisationId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getUid().isEmpty()) {
        uid_ = other.uid_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (rolesBuilder_ == null) {
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
      } else {
        if (!other.roles_.isEmpty()) {
          if (rolesBuilder_.isEmpty()) {
            rolesBuilder_.dispose();
            rolesBuilder_ = null;
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000400);
            rolesBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRolesFieldBuilder() : null;
          } else {
            rolesBuilder_.addAllMessages(other.roles_);
          }
        }
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (other.getApproved() != false) {
        setApproved(other.getApproved());
      }
      if (!other.getFeduid().isEmpty()) {
        feduid_ = other.feduid_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              firstName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              postalAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              telephone1_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              telephone2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              username_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              lastName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              organisationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              uid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              org.core.backend.Role m =
                  input.readMessage(
                      org.core.backend.Role.parser(),
                      extensionRegistry);
              if (rolesBuilder_ == null) {
                ensureRolesIsMutable();
                roles_.add(m);
              } else {
                rolesBuilder_.addMessage(m);
              }
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  getLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 104: {
              active_ = input.readBool();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              approved_ = input.readBool();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              feduid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object Id_ = "";
    /**
     * <code>string _id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = Id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        Id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string _id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = Id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string _id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      Id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string _id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      Id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string _id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      Id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      firstName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      firstName_ = getDefaultInstance().getFirstName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 2;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      firstName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object postalAddress_ = "";
    /**
     * <code>string postalAddress = 3;</code>
     * @return The postalAddress.
     */
    public java.lang.String getPostalAddress() {
      java.lang.Object ref = postalAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postalAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string postalAddress = 3;</code>
     * @return The bytes for postalAddress.
     */
    public com.google.protobuf.ByteString
        getPostalAddressBytes() {
      java.lang.Object ref = postalAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postalAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string postalAddress = 3;</code>
     * @param value The postalAddress to set.
     * @return This builder for chaining.
     */
    public Builder setPostalAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      postalAddress_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string postalAddress = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostalAddress() {
      postalAddress_ = getDefaultInstance().getPostalAddress();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string postalAddress = 3;</code>
     * @param value The bytes for postalAddress to set.
     * @return This builder for chaining.
     */
    public Builder setPostalAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      postalAddress_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object telephone1_ = "";
    /**
     * <code>string telephone1 = 4;</code>
     * @return The telephone1.
     */
    public java.lang.String getTelephone1() {
      java.lang.Object ref = telephone1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telephone1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string telephone1 = 4;</code>
     * @return The bytes for telephone1.
     */
    public com.google.protobuf.ByteString
        getTelephone1Bytes() {
      java.lang.Object ref = telephone1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telephone1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string telephone1 = 4;</code>
     * @param value The telephone1 to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone1(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      telephone1_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string telephone1 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelephone1() {
      telephone1_ = getDefaultInstance().getTelephone1();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string telephone1 = 4;</code>
     * @param value The bytes for telephone1 to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      telephone1_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object telephone2_ = "";
    /**
     * <code>string telephone2 = 5;</code>
     * @return The telephone2.
     */
    public java.lang.String getTelephone2() {
      java.lang.Object ref = telephone2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telephone2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string telephone2 = 5;</code>
     * @return The bytes for telephone2.
     */
    public com.google.protobuf.ByteString
        getTelephone2Bytes() {
      java.lang.Object ref = telephone2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telephone2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string telephone2 = 5;</code>
     * @param value The telephone2 to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone2(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      telephone2_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string telephone2 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelephone2() {
      telephone2_ = getDefaultInstance().getTelephone2();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string telephone2 = 5;</code>
     * @param value The bytes for telephone2 to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      telephone2_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 6;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 6;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 6;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      username_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      username_ = getDefaultInstance().getUsername();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string username = 6;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      username_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 7;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastName = 7;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastName = 7;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      lastName_ = getDefaultInstance().getLastName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 7;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 8;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 8;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 8;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 8;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object organisationId_ = "";
    /**
     * <code>string organisationId = 9;</code>
     * @return The organisationId.
     */
    public java.lang.String getOrganisationId() {
      java.lang.Object ref = organisationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        organisationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string organisationId = 9;</code>
     * @return The bytes for organisationId.
     */
    public com.google.protobuf.ByteString
        getOrganisationIdBytes() {
      java.lang.Object ref = organisationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        organisationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string organisationId = 9;</code>
     * @param value The organisationId to set.
     * @return This builder for chaining.
     */
    public Builder setOrganisationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      organisationId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string organisationId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrganisationId() {
      organisationId_ = getDefaultInstance().getOrganisationId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string organisationId = 9;</code>
     * @param value The bytes for organisationId to set.
     * @return This builder for chaining.
     */
    public Builder setOrganisationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      organisationId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object uid_ = "";
    /**
     * <code>string uid = 10;</code>
     * @return The uid.
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uid = 10;</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uid = 10;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uid_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      uid_ = getDefaultInstance().getUid();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 10;</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uid_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.util.List<org.core.backend.Role> roles_ =
      java.util.Collections.emptyList();
    private void ensureRolesIsMutable() {
      if (!((bitField0_ & 0x00000400) != 0)) {
        roles_ = new java.util.ArrayList<org.core.backend.Role>(roles_);
        bitField0_ |= 0x00000400;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.core.backend.Role, org.core.backend.Role.Builder, org.core.backend.RoleOrBuilder> rolesBuilder_;

    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public java.util.List<org.core.backend.Role> getRolesList() {
      if (rolesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(roles_);
      } else {
        return rolesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public int getRolesCount() {
      if (rolesBuilder_ == null) {
        return roles_.size();
      } else {
        return rolesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public org.core.backend.Role getRoles(int index) {
      if (rolesBuilder_ == null) {
        return roles_.get(index);
      } else {
        return rolesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder setRoles(
        int index, org.core.backend.Role value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolesIsMutable();
        roles_.set(index, value);
        onChanged();
      } else {
        rolesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder setRoles(
        int index, org.core.backend.Role.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.set(index, builderForValue.build());
        onChanged();
      } else {
        rolesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder addRoles(org.core.backend.Role value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
      } else {
        rolesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder addRoles(
        int index, org.core.backend.Role value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolesIsMutable();
        roles_.add(index, value);
        onChanged();
      } else {
        rolesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder addRoles(
        org.core.backend.Role.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.add(builderForValue.build());
        onChanged();
      } else {
        rolesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder addRoles(
        int index, org.core.backend.Role.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.add(index, builderForValue.build());
        onChanged();
      } else {
        rolesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder addAllRoles(
        java.lang.Iterable<? extends org.core.backend.Role> values) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roles_);
        onChanged();
      } else {
        rolesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder clearRoles() {
      if (rolesBuilder_ == null) {
        roles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
      } else {
        rolesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public Builder removeRoles(int index) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.remove(index);
        onChanged();
      } else {
        rolesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public org.core.backend.Role.Builder getRolesBuilder(
        int index) {
      return getRolesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public org.core.backend.RoleOrBuilder getRolesOrBuilder(
        int index) {
      if (rolesBuilder_ == null) {
        return roles_.get(index);  } else {
        return rolesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public java.util.List<? extends org.core.backend.RoleOrBuilder>
         getRolesOrBuilderList() {
      if (rolesBuilder_ != null) {
        return rolesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(roles_);
      }
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public org.core.backend.Role.Builder addRolesBuilder() {
      return getRolesFieldBuilder().addBuilder(
          org.core.backend.Role.getDefaultInstance());
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public org.core.backend.Role.Builder addRolesBuilder(
        int index) {
      return getRolesFieldBuilder().addBuilder(
          index, org.core.backend.Role.getDefaultInstance());
    }
    /**
     * <code>repeated .user.Role roles = 11;</code>
     */
    public java.util.List<org.core.backend.Role.Builder>
         getRolesBuilderList() {
      return getRolesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.core.backend.Role, org.core.backend.Role.Builder, org.core.backend.RoleOrBuilder>
        getRolesFieldBuilder() {
      if (rolesBuilder_ == null) {
        rolesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.core.backend.Role, org.core.backend.Role.Builder, org.core.backend.RoleOrBuilder>(
                roles_,
                ((bitField0_ & 0x00000400) != 0),
                getParentForChildren(),
                isClean());
        roles_ = null;
      }
      return rolesBuilder_;
    }

    private org.core.backend.Location location_;
    private com.google.protobuf.SingleFieldBuilder<
        org.core.backend.Location, org.core.backend.Location.Builder, org.core.backend.LocationOrBuilder> locationBuilder_;
    /**
     * <code>.user.Location location = 12;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.user.Location location = 12;</code>
     * @return The location.
     */
    public org.core.backend.Location getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? org.core.backend.Location.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    public Builder setLocation(org.core.backend.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
      } else {
        locationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    public Builder setLocation(
        org.core.backend.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    public Builder mergeLocation(org.core.backend.Location value) {
      if (locationBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          location_ != null &&
          location_ != org.core.backend.Location.getDefaultInstance()) {
          getLocationBuilder().mergeFrom(value);
        } else {
          location_ = value;
        }
      } else {
        locationBuilder_.mergeFrom(value);
      }
      if (location_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000800);
      location_ = null;
      if (locationBuilder_ != null) {
        locationBuilder_.dispose();
        locationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    public org.core.backend.Location.Builder getLocationBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    public org.core.backend.LocationOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            org.core.backend.Location.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.user.Location location = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.core.backend.Location, org.core.backend.Location.Builder, org.core.backend.LocationOrBuilder>
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.core.backend.Location, org.core.backend.Location.Builder, org.core.backend.LocationOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 13;</code>
     * @return The active.
     */
    @java.lang.Override
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 13;</code>
     * @param value The active to set.
     * @return This builder for chaining.
     */
    public Builder setActive(boolean value) {

      active_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00001000);
      active_ = false;
      onChanged();
      return this;
    }

    private boolean approved_ ;
    /**
     * <code>bool approved = 14;</code>
     * @return The approved.
     */
    @java.lang.Override
    public boolean getApproved() {
      return approved_;
    }
    /**
     * <code>bool approved = 14;</code>
     * @param value The approved to set.
     * @return This builder for chaining.
     */
    public Builder setApproved(boolean value) {

      approved_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>bool approved = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearApproved() {
      bitField0_ = (bitField0_ & ~0x00002000);
      approved_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object feduid_ = "";
    /**
     * <code>string feduid = 15;</code>
     * @return The feduid.
     */
    public java.lang.String getFeduid() {
      java.lang.Object ref = feduid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feduid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string feduid = 15;</code>
     * @return The bytes for feduid.
     */
    public com.google.protobuf.ByteString
        getFeduidBytes() {
      java.lang.Object ref = feduid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feduid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string feduid = 15;</code>
     * @param value The feduid to set.
     * @return This builder for chaining.
     */
    public Builder setFeduid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      feduid_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string feduid = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeduid() {
      feduid_ = getDefaultInstance().getFeduid();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string feduid = 15;</code>
     * @param value The bytes for feduid to set.
     * @return This builder for chaining.
     */
    public Builder setFeduidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      feduid_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:user.User)
  }

  // @@protoc_insertion_point(class_scope:user.User)
  private static final org.core.backend.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.core.backend.User();
  }

  public static org.core.backend.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.core.backend.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
