name: Deploy to Dev.

on:
  push:
    branches:
      # - dev

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_VERSION: dev-${{github.sha}}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          servers: '[{ "id": "laxnit-backend-utils", "username": "${{ secrets.MAVEN_USERNAME }}", "password": "${{ secrets.MAVEN_PASSWORD }}" }]'
          repositories: '[{ "id": "central", "name": "Maven central", "url": "https://repo1.maven.org/maven2", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },{ "id": "laxnit-backend-utils", "name": "laxnit-backend-utils", "url": "https://maven.pkg.github.com/T-Tech-LTD/laxnit-backend-utils/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install protoc-gen-grpc-java plugin
        run: |
          mkdir -p $HOME/bin
          curl -L https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.62.2/protoc-gen-grpc-java-1.62.2-linux-x86_64.exe -o $HOME/bin/protoc-gen-grpc-java
          chmod +x $HOME/bin/protoc-gen-grpc-java
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Create ProtoBufs
        run: |
          protoc --java_out=src/main/java/org/core/backend/proto --grpc-java_out=src/main/java/org/core/backend/proto src/main/java/org/core/backend/proto/*.proto
      - name: Package With Maven
        run: |
          mvn clean package -DskipTests
      - name: Build docker image
        run: |
          docker build -f src/main/docker/Dockerfile.native -t vertx/mouv-core:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: mouv-registry.dk-denno.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Tag docker image
        run: |
          docker tag vertx/mouv-core:latest mouvAfrica/mouv-core:latest
      - name: Push to registry
        run: |
          docker push mouvAfrica/mouv-core:latest

# docker stop laxnit_auth_dev; docker rm laxnit_auth_dev; sudo docker system prune -a
# docker run -d --name laxnit_auth_dev --restart unless-stopped -p 8447:8447 --env-file /opt/envars/laxnit_dev.env dkdenno/mouv-core:latest


# docker run -d --name laxnit_auth_dev --restart unless-stopped -p 8080:8080 -p 7000:7000 --env-file .env vertx/mouv-core:latest
